set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
call vundle#end()            " required
filetype plugin indent on    " required
Plugin 'AutoComplPop'
Plugin 'vim-airline/vim-airline'
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/syntastic'

set cursorline
set nu
set smartindent
set hlsearch
set tabstop=4
set shiftwidth=4
language en_US.UTF-8
let g:Powerline_symbols = 'fancy'
set laststatus=2

set listchars=tab:→\ ,trail:∙,nbsp:•
set list
colo slate
set bg=dark
syntax on
color desert
